bind score docs
mkukielka/oddt pull request #2
Opened 2019-05-23 11:11 UTC by banan314

![image](https://user-images.githubusercontent.com/17968722/58248393-46cfd680-7d5c-11e9-8915-101e3722f7e0.png)

2019-05-23 11:26 UTC, mkukielka reviewed
I think, we should adapt to current notation of documentation. So name_of_param: type_of_param ( default='sth' if exists )

e.g.
```
"""Returns pairs of atoms which are within close contac distance cutoff.
    The cutoff is semi-inclusive, i.e (cutoff_low, cutoff].
    Parameters
    ----------
    x, y : atom_dict-type numpy array
        Atom dictionaries generated by oddt.toolkit.Molecule objects.
    cutoff : float
        Cutoff distance for close contacts
    x_column, ycolumn : string, (default='coords')
        Column containing coordinates of atoms (or pseudo-atoms,
        i.e. ring centroids)
    cutoff_low : float (default=0.)
        Lower bound of contacts to find (exclusive). Zero by default.
        .. versionadded:: 0.6
    Returns
    -------
    x_, y_ : atom_dict-type numpy array
        Aligned pairs of atoms in close contact for further processing.
    """
```

2019-05-30 11:00 UTC, banan314 commented
@mkukielka done

2019-06-01 10:58 UTC, mkukielka requested changes
I know, I am a little bit harsh, but It would be nice to provide nicely done docs.

2019-06-01 10:58 UTC, mkukielka commented on oddt/docking/BindScore.py
> +        num_rotors: number
more precise, int or float?

2019-06-01 10:58 UTC, mkukielka commented on oddt/docking/BindScore.py
> +        correct radii of atoms to prepare them for scoring. The elements of concern are all metals and some nonmetals,
radii?

2019-06-01 10:58 UTC, mkukielka commented on oddt/docking/BindScore.py
> +        number
again

2019-06-01 10:58 UTC, mkukielka commented on oddt/docking/BindScore.py
> +        BindScore
param: type
    description

2019-06-11 17:19 UTC, banan314 commented on oddt/docking/BindScore.py
> +        correct radii of atoms to prepare them for scoring. The elements of concern are all metals and some nonmetals,
plural of radius

2019-06-11 21:21 UTC, mkukielka commented
conflicts, rebase to master, requested changes?

2019-06-13 11:58 UTC, mkukielka commented
If you look into current code of CustomEngine I don't know whether we still need this class.

2019-06-13 12:09 UTC, banan314 commented
> If you look into current code of CustomEngine I don't know whether we still need this class.

Oh, I just rebased it anyway

2019-06-14 18:56 UTC, banan314 commented
Closing as not needed

2019-06-14 18:56 UTC, closed without merging